SELECT * FROM People;
SELECT * FROM Customer;
SELECT * FROM Staff;
SELECT * FROM Booking;
SELECT * FROM Meal;
SELECT * FROM PlayInfo;
SELECT * FROM Play;
SELECT * FROM Ticket;
SELECT * FROM TicketInfo;